### ISSUE TITLE
[FEATURE] User Login

### ISSUE THREAD

**Issue by Robert-F-Cameron** [Robert-F-Cameron/SquadDeck#1]
## Feature: User Login

**As** a user   

**I want** to be able to login

**So that** I can save my work/unit configuration and information

Required Fields:
- [ ] E-Mail
- [ ] Password
 
Depends on:
- [ ]  #3 
## Acceptance Criteria

Scenario: Login Success
 

* **Given** I am on the login page

  * **And** I have entered the correct credentials

* **When** I click the login button

* **Then** I should be brought to my unit homepage

 

Scenario: Incorrect Credentials

* **Given** I am on the login page

  * **And** I have entered the incorrect credentials

* **When** I click the login button

* **Then** I should be shown if I have an invalid username or password

  * **And** be prompted to login again or register.

**Comment by Robert-F-Cameron** [comment]
**Weight**: 1

**Comment by officeraggro** [comment]
User login feature implemented and tested.
