### ISSUE TITLE
[FEATURE] Unit Onboarding

### ISSUE THREAD

**Issue by Robert-F-Cameron** [Robert-F-Cameron/SquadDeck#10]
Feature: Unit Onboarding
**As** a new user

**I want** be prompted to create a new unit when mine does not exist

**So that** I can start using the application with my unit
 

- [x] Unit Information

> The unit information should include
>  1. Unit Name
>  2. Unit Abbreviation
>  3. Base
>  4. Unit Workcenters

- [x] Unit Work Centers

> Unit work centers should include
> 1. Work center name
> 2. Parent work center [default to Unit]

## Acceptance Criteria

Scenario: Has successfully created an account without a Unit and is brought to the unit onboarding page
 

* **Given** The unit information is filled out 

  * **And** all of the work centers are created as a part of the unit

* **When** the form is submitted

* **Then** the unit should be created

  * **And** the member should be given the option to upload an alpha roster

 

 

Scenario: The unit information is not filled out correctly

 

* **Given** the unit creation from is missing information

* **When** the form is submitted

* **Then** there should be an error showing what information is missing
 

 

Scenario: a unit with the same name exists

 

* **Given** the unit information is filled out 

  * **And** a unit with the same name at the same base exists

* **When** the form is submitted

* **Then** there should be an error thrown showing that the unit exists

  * **And** it should return the user to select the unit on their user registration

**Comment by officeraggro** [comment]
Unit onboarding form implemented.
