### ISSUE TITLE
[FEATURE] Personnel Card Image Upload

### ISSUE THREAD

**Issue by Robert-F-Cameron** [Robert-F-Cameron/SquadDeck#12]
Feature: Personnel card image upload

**As** a user

**I want** to be able to add my picture to my personnel card

**So that** people can see who I am
 

## Acceptance Criteria

Scenario: Selects accepted img format and uploads
 

* **Given** I am editing my personnel card

  * **And** I have selected an image that is the correct format (jpg, png, etc) and smaller than `X` mb

* **When** I save my card 

* **Then** should see my image on my personnel card

 

 

Scenario: incorrect image/file is selected for upload

 
* **Given** I am editing my personnel card

  * **And** I have selected an incorrect format (not jpg, png, etc) and smaller than `X` mb

* **When** I save my card 

* **Then** should see an error that the file selected is incorrect

 

Scenario: file is too large

 
* **Given** I am editing my personnel card

  * **And** I have selected an image larger than `X` mb

* **When** I save my card 

* **Then** should see an error that the file selected is too large

**Comment by officeraggro** [comment]
Card portrait image feature implemented and tested.
