### ISSUE TITLE
[FEATURE] User Registration

### ISSUE THREAD

**Issue by Blacksheep301** [Robert-F-Cameron/SquadDeck#3]
Feature: User Registration   
**As** a User

**I want**  to be able to click on a button and register for an account

**So that** I can get access to the application

Registration Fields:
_Consider Auth0 account registration_ 
- [x] First Name *
- [x] Last Name *
- [x] E-Mail *
- [x] Password *
 - [x] Confirm Password *
- [x] Unit (Drop Down) *
 

## Acceptance Criteria

Scenario: Registration Success

 

* **Given** that I filled out my information 

  * **And** all of the fields are formatted correctly

* **When** I submit my registration

* **Then** I will receive confirmation that my registration is complete

 

 

 

Scenario: Incorrect Formatting

 

* **Given** that I filled out my information

  * **And** I did not fill out the field correctly

* **When** I submit my registration

* **Then** I will receive an error message to correct the error(s)

Scenario: Users Unit does not exist

 

* **Given** that I filled out my information

  * **And** I cannot find my Unit within the application

* **When** I submit my registration

* **Then** I will be prompted to create a new unit [see this issue](https://github.com/Robert-F-Cameron/SquadDeck/issues/10)

**Comment by Robert-F-Cameron** [comment]
**Weight**: 2

**Comment by officeraggro** [comment]
User registration feature implemented and tested.
