### ISSUE TITLE
[FEATURE] Edit/Save Personnel Cards

### ISSUE THREAD

**Issue by mangits** [Robert-F-Cameron/SquadDeck#5]
Feature: Edit/Save Personnel Cards
**As** a user

**I want** to edit and save changes to personnel cards to supplement information on the cards 

**So that** the personnel cards are up to date and personalized.

Depends On:
- [x] #17 
 

## Acceptance Criteria

Scenario: Edit your own card

* **Given** I am logged

  * **And** I have claimed a card

* **When** I flip the card I can click the edit button on my card

* **Then** my card fields will be editable

  * **And** if I click the save Icon the card edits will be stored
  * **Or** if I click off the card or an X icon the edits will be discarded.

Scenario: Edit other member's cards

* **Given** I have elevated privileges

  * **And** I want to edit my subordinates cards
 
* **When** I flip the card and click the edit button on their card

* **Then** the card fields will be editable

  * **And** if I click the save Icon the card edits will be stored
  * **Or** if I click off the card or an X icon the edits will be discarded.

**Comment by Robert-F-Cameron** [comment]
**Weight**: 2

**Comment by officeraggro** [comment]
PATCH method ready for updating cards, alpha roster verification

**Comment by officeraggro** [comment]
Card edit/save functionality implemented in UI.
